### PR TITLE
Extend range of compatible Rake versions to include 13.x

### PR DESCRIPTION
**Pull request by nearapogee**
I want to use rake 13.x. So I bumped the compatible version, and all tests pass with rake 13.0.1.

Thank you for this gem!

### CODE REVIEW

**Comment by nearapogee** [comment]
Yes! Here too please!

And you got me hooked on vlad many years ago at Cafe Vivace.... Haha.

**Comment by nearapogee** [comment]
Updated an app to rails 6.1 and it now looks like Rake 10.5 now conflicts. 

```
bundle/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:18:in `perform': undefined method `with_application' for Rake:Module (NoMethodError)
```

Sorry to be needy! Thanks @zenspider!

**Comment by zenspider** [comment]
done

**Comment by nearapogee** [comment]
Thanks!

**Pull request closed without merging**
